### ISSUE TITLE
License

### ISSUE THREAD

**Issue by neoncube2** [KostyaTretyak/ng-contenteditable#1]
Hello :)

Would you mind putting up a license for this project's code?

Thanks :)

**Comment by KostyaTretyak** [comment]
@neoncube2, now in [package.json](https://github.com/KostyaTretyak/ng-contenteditable/blob/master/package.json) is a mention of the license - MIT. I'll probably add it now.

**Comment by neoncube2** [comment]
@KostyaTretyak Thanks! Ya, I just noticed that myself, actually. I probably should have looked around more before filing an issue.

Anyway, thanks again :)

**Comment by KostyaTretyak** [comment]
Added the [LICENSE](https://github.com/KostyaTretyak/ng-contenteditable/blob/master/LICENSE)
