### ISSUE TITLE
Warning messages when using with Angular 6.1.3 and RxJs 6.2.2

### ISSUE THREAD

**Issue by micksatana** [KostyaTretyak/ng-contenteditable#10]
Hi there, thanks for making this very useful module.

There are some warning messages showing up when we use with `@angular/core@^6.1.3` and `rxjs@^6.2.2`.
```
npm WARN ng-contenteditable@2.0.1 requires a peer of @angular/core@^4.0.0but none is installed. You must install peer dependencies yourself.
npm WARN ng-contenteditable@2.0.1 requires a peer of rxjs@^5.1.0 but noneis installed. You must install peer dependencies yourself.
```

**Comment by KostyaTretyak** [comment]
@micksatana, thanks for this issue. [This code](https://github.com/KostyaTretyak/ng-contenteditable/blob/574f4482645fcac565e1c56e759bb97bf81cb05f/src/package.json#L25-L27) is the cause `npm WARN`. I'll correct it in ten hours.

But `ng-contenteditable` works correctly?

**Comment by KostyaTretyak** [comment]
@micksatana, please check work:

```bash
npm install ng-contenteditable@^2.0.2
```

**Comment by micksatana** [comment]
@KostyaTretyak Confirmed. it works! Thank you :)
