### ISSUE TITLE
[FeatureRequest] conditional contenteditable

### ISSUE THREAD

**Issue by smoebody** [KostyaTretyak/ng-contenteditable#12]
Hi, thanks for your awesome work. I would suggest a feature-request:

I would like to conditionally make an element editable by providing a boolean variable on which i can decide whether the element should be editable, e.g.:

content-element.html
```html
<p *contenteditable="isEditable" [formControl]="myControl"></p>
```

```ts
export class ContentElementComponent implements OnInit {
	isEditable = false;
	myControl = new FormControl();
	ngOnInit() {
		if (userShouldEdit()) {
			this.isEditable = true;
		}
	}
} 
```

would that be possible or somehow a bad idea?

thanks in advance

**Comment by KostyaTretyak** [comment]
@smoebody, try to do:

```base
npm i ng-contenteditable@^2.1
```
and then use like this:

```html
<p [contenteditable]="isEditable"></p>
```
