### ISSUE TITLE
Count characters and add a span around characters over limit

### ISSUE THREAD

**Issue by BenRacicot** [KostyaTretyak/ng-contenteditable#2]
Hey @KostyaTretyak this is seriously awesome work you've done here. I was hoping to ask you a question about how I might proceed with counting and displaying the characters entered and also adding a `<span>` around the characters over the limit to style them.

Would you have any advice on that?

**Comment by KostyaTretyak** [comment]
@BenRacicot, do you use template or reactive Angular forms?

**Comment by BenRacicot** [comment]
@KostyaTretyak reactive forms.

**Comment by KostyaTretyak** [comment]
In your component:
```ts
// ...
  maxLength = 5;
  myControl = new FormControl(null, Validators.maxLength(this.maxLength));
// ...
```

In your css-file:

```css
.ng-invalid {
  color: red;
}
```

In your html-template:
```html
<p [formControl]="myControl" contenteditable="true"></p>
<div *ngIf="myControl.invalid">
  over the limit: {{ myControl.value.length - maxLength }}
</div>
```

As you can see, after entering five characters, the text will become red.

**Comment by BenRacicot** [comment]
Thanks @KostyaTretyak but I'm trying to count the characters and add a `<span>` around the characters that are over the limit not validate the field. If you don't have time for this I understand, it's just that contenteditable is uncharted for me.

**Comment by KostyaTretyak** [comment]
@BenRacicot, I updated my previous answer for you.

**Comment by BenRacicot** [comment]
@KostyaTretyak I created a [StackOverflow question](https://stackoverflow.com/q/46918444/1440240) for this if you're interested. I'd also be willing to pay to get this completed.
Either way thanks for your time with me.

**Comment by KostyaTretyak** [comment]
@BenRacicot, I think for this purpose you need to use [execCommand](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand). If you open Twitter's script [this](https://abs.twimg.com/k/uk/0.commons.uk.681e1e95f36a3a010cae.js) and [this](https://abs.twimg.com/k/uk/init.uk.67f1284d1da3b8a9b542.js), you can find `execCommand`

**Comment by BenRacicot** [comment]
Is this something you would be interested in building into your repo and I will pay for your time on it?

**Comment by KostyaTretyak** [comment]
Thank you for the suggestion, but I have no experience with `execCommand`.
