### ISSUE TITLE
Getting an error when using this - angular 5

### ISSUE THREAD

**Issue by bostondevin** [KostyaTretyak/ng-contenteditable#6]
Just trying this out and getting this error - using the latest Angular 5 / CLI:

ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 404:52 in the original .ts file), resolving symbol Directive in /Users/bostondevin/Desktop/mgx/node_modules/ng-contenteditable/node_modules/@angular/core/core.d.ts, resolving symbol ContenteditableDirective in /Users/bostondevin/Desktop/mgx/node_modules/ng-contenteditable/src/index.ts, resolving symbol ContenteditableDirective in /Users/bostondevin/Desktop/mgx/node_modules/ng-contenteditable/src/index.ts

I think it's related to using the angular CLI - https://github.com/angular/angular-cli/issues/3707

**Comment by KostyaTretyak** [comment]
@bostondevin, which exactly version of angular-cli and how you run project with it?

**Comment by KostyaTretyak** [comment]
@bostondevin, try to do `npm update ng-contenteditable`
