### ISSUE TITLE
propValueAccesor is misspelled

### ISSUE THREAD

**Issue by mactyr** [KostyaTretyak/ng-contenteditable#7]
"Accessor" should have a double "s", as in `NG_VALUE_ACCESSOR`.

Caused me some confusion when I tried to set `propValueAccessor` and it didn't work! Thanks for providing the otherwise very helpful package. 👍

**Comment by KostyaTretyak** [comment]
@mactyr , thank you! Now this issue [fixed](https://github.com/KostyaTretyak/ng-contenteditable/commit/4a2ca9f996f7e75579723c09f81a654e45b549b9) and you can `npm update ng-contenteditable`

**Comment by mactyr** [comment]
Awesome. Thanks for the very prompt response.
