### ISSUE TITLE
test is not saved in IE

### ISSUE THREAD

**Issue by na-le** [KostyaTretyak/ng-contenteditable#8]
I'm using your directive and in IE 11 the text I edit is not saved in the component. (I didn't use any form)
in FF, chrome and Edge everything is OK.
here is the html:
` <div  #description class="property description"   [(ngModel)]="cellDraft.description" contenteditable="true"></div>`

**Comment by KostyaTretyak** [comment]
Sorry, IE is not supported.

**Comment by sumitdaga** [comment]
@KostyaTretyak 

you should really mention this in the README!
it otherwise works pretty nicely, except for IE 11 (it works in edge too)
do you have any workaround for IE 11 that i can use?

thanks
