### ISSUE TITLE
Error after update angular

### ISSUE THREAD

**Issue by alexander171294** [KostyaTretyak/ng-contenteditable#9]
Hi, after angular update, the plugin throw exception and isn't build, 

Check this:
![imagen](https://user-images.githubusercontent.com/2080955/40581442-b7135106-612e-11e8-9de3-c4ec8d16b8cd.png)

```
 ERROR in ./node_modules/ng-contenteditable/src/index.ts
 Module build failed: Error: D:\Usuario\Documentos\git\alumni-app\alumniApp\node_modules\ng-contenteditable\src\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
 The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
     at AngularCompilerPlugin.getCompiledFile (D:\Usuario\Documentos\git\alumni-app\alumniApp\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:709:23)
     at plugin.done.then (D:\Usuario\Documentos\git\alumni-app\alumniApp\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

But the file is in the correct location

I'm not sure why is show this error :/

Best regards.

**Comment by alexander171294** [comment]
For now, i copy the src/index.ts in my project as other directive, and work fine.

**Comment by KostyaTretyak** [comment]
@alexander171294, thank you for this issue. I plan to implement [Angular Package Format (APF) v6.0](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview) for `ng-contenteditable` in the future.

**Comment by isopen** [comment]
@alexander171294 for many occasions you can try to configure `tsconfig`
This is done so that the user knows for certain why he uses the library.
eg: https://github.com/isopen/ngx-cable/issues/4

**Comment by KostyaTretyak** [comment]
@alexander171294, check this:

```bash
npm install ng-contenteditable@^2.0.2
``` 

And then import module (not the directive), see [example](https://github.com/KostyaTretyak/ng-contenteditable#usage)

**Comment by alexander171294** [comment]
Thanks.
